// Lossless PNG optimizer for image assets tracked in the repo. Wraps the
// oxipng binary (bundled via the oxipng-bin dev dependency) which re-tries
// PNG filter strategies + optimal DEFLATE — strictly lossless, pixels are
// never altered, only the compressed stream is rewritten.
//
// Scope: assets/theme, assets/live2d (embedded into the Go binary via
// embed.FS), web/public/images (shipped by the SSG) and docs/png (repo
// weight only). assets/dist/ is the Nuxt SSG output (regenerated by
// `pnpm generate`) and is intentionally skipped. Built-in theme images
// are all WebP (lossy-converted by convert-webp.mjs) — lossless WebP
// recompression does not exist, so they are out of scope here.
//
// Usage:
//   pnpm optimize:images             optimize in place (-o 2, strip safe)
//   pnpm optimize:images --check     dry-run, report savings only (exit 1 if shrinkable)
//   pnpm optimize:images --level 4   higher = slower but smaller (0-6, default 2)
//   pnpm optimize:images --verbose   show per-file oxipng output
//
// Iron Rule 4 (server-side re-encode on upload) is unaffected: this
// script only touches pre-built-in assets, not the upload channel.
import { spawn, spawnSync } from 'node:child_process';
import { readdir, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { delimiter, dirname, join } from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const OXIPNG = join(repoRoot, 'node_modules', '.bin', 'oxipng');

// The bundled vendor binary targets one arch per install (an x86_64 build
// on arm64 fails with spawn error -86), so probe it once and fall back to
// a system-wide oxipng. pnpm prepends node_modules/.bin to PATH, so a
// bare `oxipng` would resolve straight back to the broken shim — scan
// PATH entries instead, skipping every node_modules directory.
const resolveOxipng = () => {
  const probe = (cmd) => spawnSync(cmd, ['--version'], { stdio: 'ignore' });
  if (probe(OXIPNG).status === 0) return OXIPNG;
  const names = process.platform === 'win32' ? ['oxipng.exe', 'oxipng'] : ['oxipng'];
  for (const dir of (process.env.PATH ?? '').split(delimiter)) {
    if (!dir || dir.includes('node_modules')) continue;
    for (const name of names) {
      const candidate = join(dir, name);
      if (probe(candidate).status === 0) return candidate;
    }
  }
  throw new Error('no runnable oxipng found (bundled binary incompatible, none on PATH)');
};

// oxipng 9.0 renamed --pretend to --dry-run; pick whichever this build
// understands so both the vendored old binary and a modern system one work.
const dryRunFlag = (oxipng) => {
  const help = spawnSync(oxipng, ['--help'], { encoding: 'utf8' }).stdout || '';
  return help.includes('--dry-run') ? '--dry-run' : '--pretend';
};

// Directories whose PNGs are worth optimizing.
const SCAN_DIRS = ['assets/theme', 'assets/live2d', 'web/public/images', 'docs/png'];

const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const verbose = args.includes('--verbose');
const levelIdx = args.indexOf('--level');
const level = levelIdx >= 0 && args[levelIdx + 1] ? Number(args[levelIdx + 1]) : 2;
if (!Number.isInteger(level) || level < 0 || level > 6) {
  console.error(`invalid --level: ${level} (expected 0-6)`);
  process.exit(2);
}

const collectPngs = async (dir) => {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await collectPngs(full)));
    } else if (e.isFile() && e.name.toLowerCase().endsWith('.png')) {
      out.push(full);
    }
  }
  return out;
};

const totalSize = async (files) => {
  let sum = 0;
  for (const f of files) {
    const s = await stat(f);
    sum += s.size;
  }
  return sum;
};

// Run oxipng on a batch. In check mode uses the version-appropriate
// dry-run flag (no writes) and returns stdout for savings parsing.
const runOxipng = (files, { check }, oxipng, dryFlag) => new Promise((resolve, reject) => {
  const cliArgs = ['-o', String(level), '--strip', 'safe'];
  if (check) cliArgs.push(dryFlag);
  cliArgs.push(...files);
  const child = spawn(oxipng, cliArgs, { stdio: verbose ? 'inherit' : 'pipe' });
  let stdout = '';
  if (!verbose) {
    // oxipng >=9 prints its dry-run summary on stdout; older builds used
    // stderr — capture both so savings parsing works on either.
    if (child.stdout) child.stdout.on('data', (d) => { stdout += d.toString(); });
    if (child.stderr) child.stderr.on('data', (d) => { stdout += d.toString(); });
  }
  child.on('error', reject);
  child.on('exit', (code) => {
    if (code === 0) resolve(stdout);
    else reject(new Error(`oxipng exited ${code}`));
  });
});

// Sum potential savings from dry-run output. Two formats exist:
// oxipng <9 prints per-file "...N bytes decrease" lines; >=9 prints one
// summary with Input size / Output size in bytes.
const sumDecrease = (output) => {
  let total = 0;
  for (const m of output.matchAll(/(\d+) bytes decrease/g)) {
    total += Number(m[1]);
  }
  const inB = [...output.matchAll(/Input size:.*?(\d+) bytes/g)].map((m) => Number(m[1])).pop();
  const outB = [...output.matchAll(/Output size:.*?(\d+) bytes/g)].map((m) => Number(m[1])).pop();
  if (inB !== undefined && outB !== undefined) {
    total += inB - outB;
  }
  return total;
};

const main = async () => {
  const oxipng = resolveOxipng();
  const files = [];
  for (const d of SCAN_DIRS) {
    files.push(...(await collectPngs(join(repoRoot, d))));
  }
  if (files.length === 0) {
    console.log('no PNG files found to optimize');
    return;
  }

  const before = await totalSize(files);
  const mode = checkOnly ? 'check (dry-run)' : 'optimize';
  console.log(`${mode}: ${files.length} PNG files, ${(before / 1024 / 1024).toFixed(1)} MiB total, oxipng -o ${level}`);

  if (checkOnly) {
    const out = await runOxipng(files, { check: true }, oxipng, dryRunFlag(oxipng));
    const decrease = sumDecrease(out);
    if (decrease > 0) {
      console.log(`shrinkable: ~${(decrease / 1024).toFixed(0)} KiB (${(decrease * 100 / before).toFixed(1)}%) could be saved`);
      console.log('run `pnpm optimize:images` to apply');
      process.exit(1);
    }
    console.log('all PNGs already optimal; nothing to do');
    return;
  }

  await runOxipng(files, { check: false }, oxipng, dryRunFlag(oxipng));
  const after = await totalSize(files);
  const saved = before - after;
  const pct = before > 0 ? (saved * 100 / before).toFixed(2) : '0.00';
  console.log(`done: ${(before / 1024 / 1024).toFixed(1)} MiB -> ${(after / 1024 / 1024).toFixed(1)} MiB (${(saved / 1024).toFixed(0)} KiB, ${pct}% smaller)`);
};

main().catch((err) => {
  console.error('optimize-images failed:', err.message);
  process.exit(1);
});
